spin_manifest_version = 2

[application]
authors = ["aldwinyu"]
description = ""
name = "glue-glue"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "glue-glue"

[variables]
telegram_bot_token = { required = true }

[component.glue-glue]
source = "target/glue-glue.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = [ "https://api.telegram.org" ]

[component.glue-glue.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]

[component.glue-glue.variables]
telegram_bot_token = "{{ telegram_bot_token }}"